name: spotizerr

services:
  spotizerr:
    volumes:
      - ./creds:/app/creds
      - ./config:/app/config
      - ./downloads:/app/downloads  # <-- Change this for your music library dir
      - ./logs:/app/logs  # <-- Volume for persistent logs
    ports:
      - 7171:7171
    image: cooldockerizer93/spotizerr:dev
    container_name: spotizerr-app
    restart: unless-stopped
    environment:
      - PUID=1000  # Replace with your desired user ID  | Remove both if you want to run as root (not recommended, might result in unreadable files)
      - PGID=1000  # Replace with your desired group ID | The user must have write permissions in the volume mapped to /app/downloads
      - UMASK=0022 # Optional: Sets the default file permissions for newly created files within the container.
      - REDIS_URL=redis://localhost:6379/0
      - REDIS_BACKEND=redis://localhost:6379/0
