name: spotizerr
services:
    spotizerr:
        volumes:
            - ./creds:/app/creds
            - ./downloads:/app/downloads # <-- Change this for your music library dir
        ports:
            - 7171:7171
        image: cooldockerizer93/spotizerr
